name: GitHub Actions Demo
run-name: List of Philips repositories
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: List of repositories in philips Organization
        env:
            GH_TOKEN: ${{ github.token }}
        run: |
          gh repo list philips-software --limit 200
      - run: echo " This job's status is ${{ job.status }}."
